AWSTemplateFormatVersion: 2010-09-09

Resources:
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: <VPC ID>
      CidrBlock: <Private Subnet 1 CIDR>
 
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: <VPC ID>
      CidrBlock: <Private Subnet 2 CIDR>

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: subnet group for rds
      DBSubnetGroupName: web-db-subnet-group
      SubnetIds:
        - !Ref PrivateSubnet1 #원래오류남
        - !Ref PrivateSubnet2

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: web-db
      DBInstanceIdentifier: web-db
      AvailabilityZone: ap-northeast-2
      AllocatedStorage: 1
      DBInstanceClass: db.t3.medium
      Engine: mysql
      MasterUsername: root
      MasterUserPassword: rootpassword1
      VPCSecurityGroups:
        - vpc-sg-id
      DBSubnetGroupName: web-db-subnet-group
      MultiAZ: true