AWSTemplateFormatVersion: 2010-09-09

Resources:
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-049fd765256442cd7
      CidrBlock: 192.168.192.0/19
      AvailabilityZone: ap-northeast-2a
 
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-049fd765256442cd7
      CidrBlock: 192.168.230.0/19
      AvailabilityZone: ap-northeast-2b

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: subnet group for rds
      DBSubnetGroupName: web-db-subnet-group
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBSubnetGroup
    Properties:
      DBName: webDB
      DBInstanceIdentifier: web-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      Engine: mysql
      MasterUsername: root
      MasterUserPassword: rootpassword1
      VPCSecurityGroups:
        - sg-0910431509fba56a0
        - sg-0c8c916ce0943aa26
        - sg-0bc951ad09afb9df3
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      PubliclyAccessible: true
      StorageType: gp3
