apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deploy
spec:
  selector:
    matchLabels:
      tier: back
  replicas: 2
  template:
    metadata:
      labels:
        tier: back
    spec:
      containers:
      - name: book-back
        image: 596401894998.dkr.ecr.ap-northeast-2.amazonaws.com/book-network:back
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"            
          limits:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /book_db
            name: efs-volume
        ports:
        - containerPort: 8080
        env:
          - name: DB_ADDRESS
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: address
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: name
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: password
          - name: DB_DBNAME
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: dbname
          - name: KEY
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: key
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: authkey
          - name: AUTH_ALGORITHM
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: authalgorithm
          - name: AUTH_EXP
            valueFrom:
              secretKeyRef:
                name: web-rds-secret
                key: authexp
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: efs-pvc
