apiVersion: v1
kind: Secret
metadata:
  name: web-rds-secret
type: Opaque
data:
  address: d2ViLWRiLmNycHpwNXFveWd3Ni5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  port: MzMwNg==
  name: YWRtaW4=
  password: cm9vdHBhc3N3b3JkMQ==
  dbname: QmFja2VuZERC
  key: MWM0OTk5ZmVlNmU3ZmM3MmU5ZjBiZjI1NGFkMWE5YTg=
  authkey: RXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpK
  authalgorithm: SFMyNTY=
  authexp: MzA=
